# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.3.4
_src_path: gh:algorandfoundation/algokit-python-template
author_email: jchimbo456@gmail.com
author_name: john6604
contract_name: smartcontract
deployment_language: python
preset_name: production
project_name: smartcontract

